services:
  migrations:
    image: notification-service
    command: "bun run migrate:deploy"
    build: .
    env_file:
      - ./config/.env.example
    depends_on:
      db:
        condition: service_healthy

  api:
    image: notification-service
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./config/.env.example
    command: "bun --filter=api start"
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully

  worker:
    image: notification-service
    build: .
    ports:
      - 9001:9001
    env_file:
      - ./config/.env.example
    command: "bun --filter=worker start"
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully

  redis:
    image: redis:8.0
    volumes:
      - redis_data:/data

  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ./config/db.env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:v3.5.1
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    env_file:
      - ./config/grafana.env
    ports:
      - 3001:3000
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboard-definitions:/var/lib/grafana/dashboards
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

volumes:
  redis_data:
  pg_data:
  prometheus_data:
  grafana_data:
  loki_data:
