apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          healthCheck:
            exec:
              command:
                [
                  "pg_isready",
                  "-U",
                  "notification_user",
                  "-d",
                  "notification_db",
                ]
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
    - port: 5432
  selector:
    app: db
