apiVersion: v2
name: platform-observability-stack
description: End-to-end observability (LGTM + Alloy + MinIO)
version: 1.0.0
dependencies:
  - name: alloy
    version: 1.10.1
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
  - name: loki
    version: 18.5.0
    repository: https://grafana-community.github.io/helm-charts
    # condition: loki.enabled
  - name: prometheus
    version: 29.17.0
    repository: https://prometheus-community.github.io/helm-charts
    # condition: prometheus.enabled
  - name: tempo
    version: 2.2.3
    repository: https://grafana-community.github.io/helm-charts
    # condition: prometheus.enabled
  - name: grafana
    version: 10.5.15
    repository: https://grafana.github.io/helm-charts
    # condition: grafana.enabled
