alloy:
  enabled: true
  alloy:
    extraPorts:
      - name: loki-api
        port: 9999
        targetPort: 9999
        protocol: TCP

    configMap:
      create: true
      content: |-
        loki.source.api "app_logs_receiver" {
          http {
            listen_address = "0.0.0.0"
            listen_port = 9999
          }
          forward_to = [loki.write.real_loki.receiver]
        }

        loki.write "real_loki" {
          endpoint {
            url = "http://observability-stack-app-loki-gateway.kofta.svc.cluster.local/loki/api/v1/push"
          }
        }
        
        discovery.kubernetes "namespace_pods" {
          role = "pod"
          namespaces {
            names = ["kofta"] 
          }
        }

        prometheus.scrape "app_metrics_scraper" {
          targets    = discovery.kubernetes.namespace_pods.targets
          forward_to = [prometheus.remote_write.prom_storage.receiver]
          scrape_interval = "15s"
        }

        prometheus.remote_write "prom_storage" {
          endpoint {
            url = "http://prometheus-operated.kofta.svc.cluster.local:9090/api/v1/write"
          }
        }

  # controller:
  #   extraAnnotations:
  #     argocd.argoproj.io/sync-wave: "-1"

  # serviceAccount:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: "-1"

  # service:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: "-1"

loki:
  enabled: true
  deploymentMode: SingleBinary

  minio:
    enabled: false

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 10Gi 

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomPlanner:
    replicas: 0
  bloomBuilder:
    replicas: 0
  bloomGateway:
    replicas: 0

prometheus:
  enabled: true
