alloy:
  enabled: true
  alloy:
    extraPorts:
      - name: loki-api
        port: 9999
        targetPort: 9999
        protocol: TCP

    configMap:
      create: true
      content: |-
        loki.source.api "app_logs_receiver" {
          http {
            listen_address = "0.0.0.0"
            listen_port = 9999
          }
          forward_to = [loki.write.real_loki.receiver]
        }

        loki.write "real_loki" {
          endpoint {
            url = "http://loki.kofta.svc.cluster.local:3100/loki/api/v1/push"
          }
        }

  # controller:
  #   extraAnnotations:
  #     argocd.argoproj.io/sync-wave: "-1"

  # serviceAccount:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: "-1"

  # service:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: "-1"

loki:
  enabled: true
  deploymentMode: Monolithic
  singleBinary:
    replicas: 1
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomPlanner:
    replicas: 0
  bloomBuilder:
    replicas: 0
  bloomGateway:
    replicas: 0

  loki:
    useTestSchema: true
    storage:
      type: "filesystem"
      bucketNames:
        chunks: "chunks"
        ruler: "ruler"
prometheus:
  enabled: true
