apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kofta999/notification-service.git'
    targetRevision: master
    path: k8s/o11y
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kofta 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true